services:
  app:
    build: ./app

    depends_on:
      db:
        condition: service_started

    volumes:
      - django_data:/var/www/app

    networks:
      - webapps

    ports:
      - 8000:8000

    env_file:
      - production.env

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    networks:
      - webapps

    env_file:
      - production.env


volumes:
  postgres_data:
  django_data:

networks:
  webapps:
    name: webapps
    external: true