services:
  app:
    build: ./app

    volumes:
      - django_data:/var/www/app

    networks:
      - webapps
    
    ports:
      - 8080:8080

    env_file:
      - development.env

volumes:
  django_data:

networks:
  webapps:
    name: webapps
    external: true