services:
  app:
    build: ./app

    volumes:
      - django_data:/var/www/app

    networks:
      - djangoweb
    
    ports:
      - 80:8080

    env_file:
      - env/development.env

volumes:
  django_data:

networks:
  webapps:
    name: djangoweb