services:
  app:
    build: ./app

    depends_on:
      db:
        condition: service_started

    volumes:
      - django_data:/var/www/app

    networks:
      - djangoweb

    env_file:
      - env/database.env
      - env/production.env

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    networks:
      - djangoweb

    env_file:
      - env/database.env

  nginx:
    build: ./nginx

    depends_on:
      app:
        condition: service_started

    volumes:
      - django_data:/var/www/app
      - nginx_certificates:/etc/ssl

    networks:
      - djangoweb

    ports:
      - 80:80
      - 443:443

    env_file:
      - env/production.env


volumes:
  postgres_data:
  django_data:
  nginx_certificates:

networks:
  djangoweb:
    name: djangoweb